### ISSUE TITLE
where to get riscv programming tools - GCC utils, etc?

### ISSUE THREAD

**Issue by agrobman** [chipsalliance/Cores-SweRV-Support-Package#3]
Does anybody maintain RISCV tools binaries as a linux package? Where to get one? 
I've found one RISCV tools package for ubuntu, but SweRV test examples do not compile with it ..
It will help to many and save a lot of time and disc space..

**Comment by ZvonimirBandic** [comment]
Did you ask Ofer?

**Comment by agrobman** [comment]
I did not ask Ofer due holidays , but since chipsalliance supports RISCV - it should be reasonable to find all needed for RISCV promotion here or at least pointers to needed stuff.. ( it was very disappointing to find that the ubuntu RISCV tools package does not work with SweRV)
And It was not clear what the RISCV tools configuration/flavor  to build from the tools sources ... it took me a few trials to find correct one.

**Comment by Codasip** [comment]
This is the right repository for you. Please install SSP according to README and you will find GNU tools you need. They are built for SweRV Core configuration, and they are proven to work properly. There is  also comprehensive documentation describing how to compile and run different benchmarks and mentioned test examples  on SweRV Core EH1,EH2 and EL2 and much more. Tools are running on CentOS7 within docker environment, however you can use ssh to login, you can mount your disk drive there, and you can also program your FPGA board from there.  If you insist of having GNU tools for SweRV running on Ubuntu, please let me know which version of Ubuntu you are using.

**Comment by agrobman** [comment]
I use latest ubuntu 10.04, I think.

**Comment by Codasip** [comment]
Latest ubuntu is 20.04. 

I have checked the RISC-V GNU toolchain built for SSP 3.0.10 and it seem to be  running well on Ubuntu 18.04.5 LTS. It means you can install SSP, go to /prj/ssp/tool/open/ and you will find the toolchain there. You can extract it and use it on your desired location however I strongly recommend you to make first steps within SSP docker environment. Here is a part of the swervolf-software-demos.pdf available in SSP describing some details:

It is strongly recommended to use GNU toolchain (riscv32-unknown-elf-*) provided with the SSP. This is because not all binary distributions of RISC-V GCC are born equal (!). Third-party builds of GCC may not work as required. Two important properties of the GNU toolchain distributed with SSP are:

* In toolchain from SSP, libgloss library is not linked into the resulting firmware by default. Libgloss is a part of newlib standard C library and implements ECALL-based system calls (traps) to a host kernel, which is however unwanted in bare metal code. For that reason, libgloss library must not be linked with the bare-metal executable.
* Newlib standard library for RV32IMC is available for use with the SSP GNU toolchain. Other 3rd-party binary distributions of GCC need not have the standard C library pre-compiled for 32-bit IMC machines, resulting in a sub-optimal compilation result (larger binaries).

Do not use OpenOCD installed as a package from your Linux distribution. As RISC-V support is a relatively new feature in OpenOCD, your Linux distribution will probably offer only an outdated OpenOCD version, lacking proper RISC-V support (or not supporting RISC-V at all).

**Comment by agrobman** [comment]
Seems swerv EH1 repo suggests to use riscv64_unknown_elf with mabi-ilp32 and march-rv32gc (?)
Do I need to install tools versions exactly matching processor I'm using? it becomes very inconvenient if one uses different processor flavors. I've heard that multilib tools version can support all riscv processor flavors ...

**Comment by Codasip** [comment]
It is true - multilib tools can support several but not all riscv processor flavors. You just need to select which mabi and march you want to have. The default toolchain compilation setup is in your case 64b. So riscv64_unknown_elf with mabi-ilp32 and march-rv32gc can be used for SweRV (RV32-IMC). If it works for you and you are sat, you need not to do anything else.

In SSP we compiled toolchain where mabi-ilp32 and march-rv32gc are used as a default configuration, removed libgloss and added RV32IMC for better code efficiency. RISC-V GNU toolchain within SSP is also multilib so you need not to install another toolchain for the other mainstream 32,64b RV configurations. You just need to select desired mabi and march from available options.

Originally you have asked for RISC-V GNU toolchain binaries for Linux which can compile SweRV EH1 examples. SSP contains both. Toolchain and examples. Additionally there is a step by step description through the flow and further proven examples.

Please let me know if it helped to solve your problem.

**Comment by agrobman** [comment]
thanks, for explanations. I actually got what I needed by compiling the tools from git sources, spending quite a time. Just thought about others not to repeat my path and save time ..

BTW, does your RISCV package support 64 bit core versions? (I've built 64 bit one with 32 bit support, which I believe universal kind ..)

**Comment by Codasip** [comment]
Yes. RISC-V GNU toolchain within SSP supports also 64bit core versions (probably very similar set of what you have compiled).

As written, primary aim of SSP (SweRV Core Support Package) is to provide proven development environment for SweRV Cores in one package - SDK, HDK, benchmarks, examples, documentation. Therefore are defaults  set to fit SweRV Core family members. It seems to me you could save a lot of time and questions by starting with SSP ....

If you already compiled the tools from git sources and they are working well for your SweRV core applications, you may probably close this issue unless you have any other questions about RISC-V GNU tools support for SweRV Cores.
